// ---------------------------------------------------------------------------------------------------------------
// Magic Fountain
// by Hannes Rydén, april 2008
// ---------------------------------------------------------------------------------------------------------------
system MagicFountain1
{
	technique
	{
		renderer				Billboard
		{
			billboard_type			point
		}

		material				ParticleUniverse/MagicFountainDrop
		default_particle_width			2
		default_particle_height			2
		visual_particle_quota		1000	
		
		emitter					Point
		{
			// Position adjusted for use with Particle Universe Viewer
			position			0 0 0
			emission_rate			40
			angle				15
			direction			0 1 0
			velocity			dyn_random
			{
				min		5	
				max		20
			}
			time_to_live		 3
		}

		affector				PlaneCollider
		{
			position			0 -0.1 0
			plane_collider_normal		0 1 0
			collision_intersection		point
			collision_type			bounce

			// friction and bouncyness decrease rotation speed and velocity
			collision_friction		0.7
			collision_bouncyness		0.2

		}

		affector				TextureRotator
		{
			// Decrease of rotation speed if a particle collides is only possible if the particle controls 
			// its own rotation speed.
			tex_rot_use_own_rotation	true
			tex_rot_speed			0
		}

		affector				LinearForce
		{
			force_aff_vector		0 -15 0
		}

		affector				Colour
		{
			colour_aff_time_colour		0 1 1 1 0
			colour_aff_time_colour		0.05 0.2 0 0.1 1
			colour_aff_time_colour		0.3 1 0.8 0.9 1
			colour_aff_time_colour		0.4 1 0.8 0.9 1
			colour_aff_time_colour		0.7 0.2 0 0.1 1
			colour_aff_time_colour		0.8 0.2 0 0.1 1
			colour_aff_time_colour		0.85 1 0.8 0.9 1			
			colour_aff_time_colour		1 0 0 0 0
		}
	}
}

system MagicFountain2
{
	technique
	{
		renderer				Billboard
		{
			billboard_type			point
		}

		material				ParticleUniverse/MagicFountainDrop
		default_particle_width			180
		default_particle_height			180
		visual_particle_quota			4000
		
		emitter					Point
		{
			// Position adjusted for use with Particle Universe Viewer
			position			0 -290 -100
			emission_rate			50
			angle				13
			direction			0 1 0
			velocity			dyn_random
			{
				min			500
				max			700
			}
			time_to_live			8
		}

		affector				PlaneCollider
		{
			position			0 -300 0
			plane_collider_normal		0 1 0
			collision_intersection		point
			collision_type			bounce

			// friction and bouncyness decrease rotation speed and velocity
			collision_friction		0.7
			collision_bouncyness		0.2

		}

		affector				TextureRotator
		{
			// Decrease of rotation speed if a particle collides is only possible if the particle controls 
			// its own rotation speed.
			tex_rot_use_own_rotation	true
			tex_rot_speed			5
		}

		affector				LinearForce
		{
			force_aff_vector		0 -400 0
		}

		affector				Colour
		{
			colour_aff_time_colour		0 1 0.5 0.5 1
			colour_aff_time_colour		0.5 1 0.5 0.5 1
			colour_aff_time_colour		0.7 0.7 0.1 0.1 1
			colour_aff_time_colour		1 0 0 0 0
		}
	}
}


system MagicFountain3
{
	technique
	{
		renderer				Billboard
		{
			billboard_type			point
		}

		material				ParticleUniverse/MagicFountainDrop
		default_particle_width			120
		default_particle_height			120
		visual_particle_quota			4000
		
		emitter					Point
		{
			// Position adjusted for use with Particle Universe Viewer
			position			0 -490 -2000
			emission_rate			600
			angle				15
			direction			0 1 0
			velocity			dyn_random
			{
				min			2000
				max			2500
			}
			time_to_live			3
		}

		affector				PlaneCollider
		{
			position			0 -500 0
			plane_collider_normal		0 1 0
			collision_intersection		point
			collision_type			bounce

			// friction and bouncyness decrease rotation speed and velocity
			collision_friction		0.7
			collision_bouncyness		0.2

		}

		affector				TextureRotator
		{
			// Decrease of rotation speed if a particle collides is only possible if the particle controls 
			// its own rotation speed.
			tex_rot_use_own_rotation	true
			tex_rot_speed			10
		}

		affector				LinearForce
		{
			force_aff_vector		0 -2500 0
		}

		affector				Colour
		{
			colour_aff_time_colour		0 0.6 0.7 0.8 1
			colour_aff_time_colour		0.5 0.6 0.7 0.8 1
			colour_aff_time_colour		1 0 0 0 0
		}
	}
}

system MagicFountain4
{
	technique
	{
		renderer				Billboard
		{
			billboard_type			point
		}

		material				ParticleUniverse/MagicFountainDrop
		default_particle_width			120
		default_particle_height			120
		visual_particle_quota			4000
		
		emitter					Point
		{
			// Position adjusted for use with Particle Universe Viewer
			position			0 -490 -2000
			emission_rate			600
			angle				30
			direction			0 1 0
			velocity			dyn_random
			{
				min			3000
				max			3000
			}
			time_to_live			1.5
		}

		affector				PlaneCollider
		{
			position			0 -500 0
			plane_collider_normal		0 1 0
			collision_intersection		point
			collision_type			bounce

			// friction and bouncyness decrease rotation speed and velocity
			collision_friction		0.7
			collision_bouncyness		0

		}

		affector				TextureRotator
		{
			// Decrease of rotation speed if a particle collides is only possible if the particle controls 
			// its own rotation speed.
			tex_rot_use_own_rotation	true
			tex_rot_speed			0
		}

		affector				LinearForce
		{
			force_aff_vector		0 -7000 0
		}

		affector				Colour
		{
			colour_aff_time_colour		0 1 0.8 0.8 1
			colour_aff_time_colour		0.7 1 0.8 0.8 1
			colour_aff_time_colour		1 0 0 0 0
		}
	}
}

system MagicFountain5
{
	technique
	{
		renderer				Billboard
		{
			billboard_type			point
		}

		material				ParticleUniverse/MagicFountainDrop
		default_particle_width			5
		default_particle_height			5
		visual_particle_quota			4000
		
		emitter					Point
		{
			// Position adjusted for use with Particle Universe Viewer
			position			0 0 0
			emission_rate			5
			angle				10
			direction			0 1 0
			velocity			dyn_random
			{
				min			200
				max			200
			}
			time_to_live			17
		}

		affector				PlaneCollider
		{
			position			0 -250 0
			plane_collider_normal		0 1 0
			collision_intersection		point
			collision_type			bounce

			// friction and bouncyness decrease rotation speed and velocity
			collision_friction		0.7
			collision_bouncyness		0.2

		}

		affector				TextureRotator
		{
			// Decrease of rotation speed if a particle collides is only possible if the particle controls 
			// its own rotation speed.
			tex_rot_use_own_rotation	true
			tex_rot_speed			1
		}

		affector				LinearForce
		{
			force_aff_vector		0 -40 0
		}

		affector				Colour
		{
			colour_aff_time_colour		0 0 0 0 0
			colour_aff_time_colour		0.1 0.8 1 1 1
			colour_aff_time_colour		0.4 0.8 1 1 1
			colour_aff_time_colour		0.6 0.8 0.9 0.9 1
			colour_aff_time_colour		0.7 0.8 0.8 0.8 1
			colour_aff_time_colour		0.8 0.8 0.7 0.7 1
			colour_aff_time_colour		0.9 0.7 0.4 0.4 1
			colour_aff_time_colour		1 0 0 0 0
		}
	}
}

system AssBang
{
	technique
	{
		renderer				Billboard
		{
			billboard_type			point
		}

		material				ParticleUniverse/MagicFountainDrop
		default_particle_width			2
		default_particle_height			2
		visual_particle_quota		1000	
		
		emitter					Point
		{
			// Position adjusted for use with Particle Universe Viewer
			position			0 -0.5 -0.5
			emission_rate			600
			angle				5
			direction			0 0 -1
			velocity			dyn_random
			{
				min		5	
				max		20
			}
			time_to_live		 1.4
		}

		affector				PlaneCollider
		{
			position			0 -10 0
			plane_collider_normal		0 1 0
			collision_intersection		point
			collision_type			bounce

			// friction and bouncyness decrease rotation speed and velocity
			collision_friction		0.7
			collision_bouncyness		0.2

		}

		affector				TextureRotator
		{
			// Decrease of rotation speed if a particle collides is only possible if the particle controls 
			// its own rotation speed.
			tex_rot_use_own_rotation	true
			tex_rot_speed			0
		}

		affector				LinearForce
		{
			force_aff_vector		0 -1 0
		}

		affector				Colour
		{
			colour_aff_time_colour		0 0 0.1 0.4 0.1
			colour_aff_time_colour		0.2 0.5 0.5 0 1
			colour_aff_time_colour		0.5 0.5 0 0 1
			colour_aff_time_colour		1 0 0 0 0
		}
	}
}

system ShinyPath
{
	technique
	{
		renderer				Billboard
		{
			billboard_type			point
		}

		material				ParticleUniverse/MagicFountainDrop
		default_particle_width			2
		default_particle_height			2
		visual_particle_quota		3000	
		
		emitter					Point
		{
			// Position adjusted for use with Particle Universe Viewer
			position			0 -1.5 0
			emission_rate	10	
			angle				180
			direction			0 0 -1
			velocity		  dyn_random
      {
        max 3
        min 1
      }
			time_to_live		 5
		}

		affector				PlaneCollider
		{
			position			0 -1.7 0
			plane_collider_normal		0 1 0
			collision_intersection		point
			collision_type			bounce

			// friction and bouncyness decrease rotation speed and velocity
			collision_friction		0.7
			collision_bouncyness		0.2

		}

		affector				TextureRotator
		{
			// Decrease of rotation speed if a particle collides is only possible if the particle controls 
			// its own rotation speed.
			tex_rot_use_own_rotation	true
			tex_rot_speed			0
		}

		affector				LinearForce
		{
			force_aff_vector		0 -1 0
		}

		affector				Colour
		{
			colour_aff_time_colour		0 1 1 1 0
			colour_aff_time_colour		0.05 0.2 0 0.1 1
			colour_aff_time_colour		0.3 1 0.8 0.9 1
			colour_aff_time_colour		0.4 1 0.8 0.9 1
			colour_aff_time_colour		0.7 0.2 0 0.1 1
			colour_aff_time_colour		0.8 0.2 0 0.1 1
			colour_aff_time_colour		0.85 1 0.8 0.9 1			
			colour_aff_time_colour		1 0 0 0 0
		}
	}
}
