
set(SCENE_PARSER_ROOT_DIR
  "${SCENE_PARSER_ROOT_DIR}"
  CACHE
  PATH
  "Path to search for scene parser plugin")

FIND_LIBRARY(SCENE_PARSER_LIBRARY
  NAMES libOgreSceneParserPlugin.so
  HINTS
  ${SCENE_PARSER_ROOT_DIR}
  PATH_SUFFIXES lib64 lib lib/OGRE lib64/OGRE
  PATHS
  /usr/local
)

message(${SCENE_PARSER_LIBRARY})

FIND_PATH(SCENE_PARSER_INCLUDE_DIR SceneFileManager.h
  HINTS
  ${SCENE_PARSER_ROOT_DIR}
  PATH_SUFFIXES include/Plugin_SceneParser
  PATHS
  /usr/local
)

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(Plugin_SceneParser SCENE_PARSER_LIBRARY SCENE_PARSER_INCLUDE_DIR)

MARK_AS_ADVANCED(SCENE_PARSER_LIBRARY SCENE_PARSER_INCLUDE_DIR)

